export const SERVICE_TIERS = [
  {
    id: 'starter',
    name: 'Starter',
    slug: 'starter',
    price: 2500,
    description: 'Perfect for small businesses getting started',
    features: [
      'Custom website design',
      'Up to 5 pages',
      'Mobile responsive',
      'Basic SEO optimization',
      '30 days support',
      '2 rounds of revisions',
    ],
    highlighted: false,
    category: 'service_tier' as const,
  },
  {
    id: 'growth',
    name: 'Growth',
    slug: 'growth',
    price: 7500,
    description: 'Ideal for growing businesses ready to scale',
    features: [
      'Everything in Starter',
      'Up to 15 pages',
      'Advanced SEO package',
      'Content management system',
      'E-commerce integration',
      '90 days support',
      'Unlimited revisions',
      'Social media setup',
    ],
    highlighted: true,
    category: 'service_tier' as const,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    slug: 'enterprise',
    price: 15000,
    description: 'Complete solution for established businesses',
    features: [
      'Everything in Growth',
      'Unlimited pages',
      'Custom web application',
      'Advanced integrations',
      'Dedicated account manager',
      '1 year support',
      'Priority support',
      'Monthly strategy calls',
      'Performance optimization',
      'Security audit',
    ],
    highlighted: false,
    category: 'service_tier' as const,
  },
] as const

export type ServiceTier = (typeof SERVICE_TIERS)[number]
